/* eslint-disable no-unused-vars */
/*eslint-disableno-unused-vars*/
import {
  FaUssunnah,
  FaFrown,
  FaGrin,
  FaGrinAlt,
  FaGrinBeam,
  FaGrinBeamSweat,
  FaGrinHearts,
  FaGrinSquint,
  FaGrinSquintTears,
  FaGrinStars,
  FaGrinTears,
  FaGrinTongue,
  FaGrinTongueSquint,
  FaGrinTongueWink,
  FaGrinWink,
  FaHammer,
  FaHandHolding,
  FaHandHoldingHeart,
  FaHandHoldingMedical,
  FaHandHoldingUsd,
  FaHandHoldingWater,
  FaHandPaper,
  FaHandRock,
  FaHanukiah,
  FaHatCowboy,
  FaHatCowboySide,
  FaHatWizard,
  FaHeadphones,
  FaHeadphonesAlt,
  FaHeadset,
  FaKiss,
  FaKissBeam,
  FaKissWinkHeart,
  FaKiwiBird,
  FaLaugh,
  FaLaughBeam,
  FaLaughSquint,
  FaLaughWink,
  FaHelicopter,
  FaHiking,
  FaHippo,
  FaHornbill,
  FaHorseHead,
  FaHotTub,
  FaHotdog,
  FaIgloo,
  FaJoomla,
  FaJournalWhills,
  FaKaaba,
  FaKeycdn,
  FaKhanda,
  FaFrownOpen,
  Fa500Px,
  FaAccessibleIcon,
  FaAccusoft,
  FaAcquisitionsIncorporated,
  FaAd,
  FaAddressBook,
  FaAddressCard,
  FaAdjust,
  FaAdn,
  FaAdversal,
  FaAffiliatetheme,
  FaAirFreshener,
  FaAirbnb,
  FaAlgolia,
  FaAllergies,
  FaAmazonPay,
  FaAmericanSignLanguageInterpreting,
  FaAngry,
  FaAngrycreative,
  FaAnkh,
  FaApper,
  FaArchway,
  FaArrowAltCircleDown,
  FaAsymmetrik,
  FaAsterisk,
  FaAtom,
  FaBabyCarriage,
  FaAutoprefixer,
  FaBaby,
  FaAvianex,
  FaBalanceScale,
  FaBandcamp,
  FaBaseballBall,
  FaBath,
  FaBattleNet,
  FaBeer,
  FaBiking,
  FaBinoculars,
  FaBirthdayCake,
  FaBlog,
  FaBomb,
  FaBone,
  FaBong,
  FaBrain,
  FaBoxOpen,
  FaBriefcaseMedical,
  FaBuilding,
  FaBullhorn,
  FaBus,
  FaBusinessTime,
  FaCameraRetro,
  FaCamera,
  FaCampground,
  FaCannabis,
  FaCat,
  FaChessKnight,
  FaChessQueen,
  FaChurch,
  FaCity,
  FaCloudflare,
  FaCode,
  FaComments,
  FaCommentMedical,
  FaCompass,
  FaCookie,
  FaCreditCard,
  FaCriticalRole,
  FaCrown,
  FaCrow,
  FaCrosshairs,
  FaCubes,
  FaCube,
  FaDesktop,
  FaDiceD20,
  FaDigitalOcean,
  FaDochub,
  FaDove,
  FaDolly,
  FaDraftingCompass,
  FaDragon,
  FaDrawPolygon,
  FaDribbble,
  FaDribbbleSquare,
  FaDrupal,
  FaDrumSteelpan,
  FaDyalog,
  FaElementor,
  FaEnvira,
  FaEmpire,
  FaEmber,
  FaEthereum,
  FaExclamationCircle,
  FaEthernet,
  FaEuroSign,
  FaFaucet,
  FaFax,
  FaFeather,
  FaFedora,
  FaFish,
  FaFistRaised,
  FaFlushed,
  FaFly,
  FaForumbee,
  FaFortAwesomeAlt,
  FaFrog,
  FaGalacticRepublic,
  FaGalacticSenate,
  FaGavel,
  FaGlassMartiniAlt,
  FaGlobe,
  FaGlasses,
  FaGlassCheers,
  FaGitlab,
  FaGitkraken,
  FaGlobeEurope,
  FaGrav,
  FaKey,
  FaPiggyBank,
  FaQuidditch,
  FaRobot,
  FaRoad,
  FaRocket,
  FaRust,
  FaSatellite,
  FaSatelliteDish,
  FaSchool,
  FaShapes,
  FaSkating,
  FaSleigh,
  FaSmoking,
  FaSmokingBan,
  FaStethoscope,
  FaUserNurse,
  FaUtensils,
  FaYammer,
  FaYarn,
  FaYinYang,
  FaWizardsOfTheCoast,
  FaWaze,
  FaWeebly,
  FaJenkins,
} from "react-icons/fa";

export const iconList = [
  { component: FaUssunnah },
  { component: FaFrown },
  { component: FaGrin },
  { component: FaGrinAlt },
  { component: FaGrinBeam },
  { component: FaGrinBeamSweat },
  { component: FaGrinHearts },
  { component: FaGrinSquint },
  { component: FaGrinSquintTears },
  { component: FaGrinStars },
  { component: FaGrinTears },
  { component: FaGrinTongue },
  { component: FaGrinTongueSquint },
  { component: FaGrinTongueWink },
  { component: FaGrinWink },
  { component: FaHammer },
  { component: FaHandHolding },
  { component: FaHandHoldingHeart },
  { component: FaHandHoldingMedical },
  { component: FaHandHoldingUsd },
  { component: FaHandHoldingWater },
  { component: FaHandPaper },
  { component: FaHandRock },
  { component: FaHanukiah },
  { component: FaHatCowboy },
  { component: FaHatCowboySide },
  { component: FaHatWizard },
  { component: FaHeadphones },
  { component: FaHeadphonesAlt },
  { component: FaHeadset },
  { component: FaKiss },
  { component: FaKissBeam },
  { component: FaKissWinkHeart },
  { component: FaKiwiBird },
  { component: FaLaugh },
  { component: FaLaughBeam },
  { component: FaLaughSquint },
  { component: FaLaughWink },
  { component: FaHelicopter },
  { component: FaHiking },
  { component: FaHippo },
  { component: FaHornbill },
  { component: FaHorseHead },
  { component: FaHotTub },
  { component: FaHotdog },
  { component: FaIgloo },
  { component: FaJoomla },
  { component: FaJournalWhills },
  { component: FaKaaba },
  { component: FaKeycdn },
  { component: FaKhanda },
  { component: FaFrownOpen },

  { component: FaAccessibleIcon },
  { component: FaAccusoft },
  { component: FaAcquisitionsIncorporated },
  { component: FaAd },
  { component: FaAddressBook },
  { component: FaAddressCard },
  { component: FaAddressCard },
  { component: FaAdjust },
  { component: FaAdn },
  { component: FaAdversal },
  { component: FaAffiliatetheme },
  { component: FaAirFreshener },
  { component: FaAirbnb },
  { component: FaAlgolia },
  { component: FaAllergies },
  { component: FaAmazonPay },
  { component: FaAmericanSignLanguageInterpreting },
  { component: FaAngry },
  { component: FaAngrycreative },
  { component: FaAnkh },
  { component: FaApper },
  { component: FaArchway },
  { component: FaArrowAltCircleDown },
  { component: FaAsymmetrik },
  { component: FaAsterisk },
  { component: FaAtom },
  { component: FaBabyCarriage },
  { component: FaAutoprefixer },
  { component: FaBaby },
  { component: FaAvianex },
  { component: FaBalanceScale },
  { component: FaBandcamp },
  { component: FaBaseballBall },
  { component: FaBath },
  { component: FaBattleNet },
  { component: FaBeer },
  { component: FaBiking },
  { component: FaBinoculars },
  { component: FaBirthdayCake },
  { component: FaBlog },
  { component: FaBomb },
  { component: FaBone },
  { component: FaBong },
  { component: FaBrain },
  { component: FaBoxOpen },
  { component: FaBriefcaseMedical },
  { component: FaBuilding },
  { component: FaBullhorn },
  { component: FaBus },
  { component: FaBusinessTime },
  { component: FaCameraRetro },
  { component: FaCamera },
  { component: FaCampground },
  { component: FaCannabis },
  { component: FaCat },
  { component: FaChessKnight },
  { component: FaChessQueen },
  { component: FaChurch },
  { component: FaCity },
  { component: FaCloudflare },
  { component: FaCode },
  { component: FaComments },
  { component: FaCommentMedical },
  { component: FaCompass },
  { component: FaCookie },
  { component: FaCreditCard },
  { component: FaCriticalRole },
  { component: FaCrown },
  { component: FaCrow },
  { component: FaCrosshairs },
  { component: FaCubes },
  { component: FaCube },
  { component: FaDesktop },
  { component: FaDiceD20 },
  { component: FaDigitalOcean },
  { component: FaDochub },
  { component: FaDove },
  { component: FaDolly },
  { component: FaDraftingCompass },
  { component: FaDragon },
  { component: FaDrawPolygon },
  { component: FaDribbble },
  { component: FaDribbbleSquare },
  { component: FaDrupal },
  { component: FaDrumSteelpan },
  { component: FaDyalog },
  { component: FaElementor },
  { component: FaEnvira },
  { component: FaEmpire },
  { component: FaEmber },
  { component: FaEthereum },
  { component: FaExclamationCircle },
  { component: FaEthernet },
  { component: FaEuroSign },
  { component: FaExclamationCircle },
  { component: FaFeather },
  { component: FaFedora },
  { component: FaFish },
  { component: FaFistRaised },
  { component: FaFlushed },
  { component: FaFly },
  { component: FaForumbee },
  { component: FaFortAwesomeAlt },
  { component: FaFrog },
  { component: FaGalacticRepublic },
  { component: FaGalacticSenate },
  { component: FaGavel },
  { component: FaGlassMartiniAlt },
  { component: FaGlobe },
  { component: FaGlasses },
  { component: FaGlassCheers },
  { component: FaGitlab },
  { component: FaGitkraken },
  { component: FaGlobeEurope },
  { component: FaGrav },
  { component: FaKey },
  { component: FaPiggyBank },
  { component: FaQuidditch },
  { component: FaRobot },
  { component: FaRoad },
  { component: FaRocket },
  { component: FaRust },
  { component: FaSatellite },
  { component: FaSatelliteDish },
  { component: FaSchool },
  { component: FaShapes },
  { component: FaSkating },
  { component: FaSleigh },
  { component: FaSmoking },
  { component: FaSmokingBan },
  { component: FaStethoscope },
  { component: FaStethoscope },
  { component: FaUserNurse },
  { component: FaUtensils },
  { component: FaYammer },
  { component: FaYarn },
  { component: FaYinYang },
  { component: FaWizardsOfTheCoast },
  { component: FaWaze },
  { component: FaWeebly },
  { component: FaJenkins },
];
export const IconName = [
  FaUssunnah,
  FaFrown,
  FaGrin,
  FaGrinAlt,
  FaGrinBeam,
  FaGrinBeamSweat,
  FaGrinHearts,
  FaGrinSquint,
  FaGrinSquintTears,
  FaGrinStars,
  FaGrinTears,
  FaGrinTongue,
  FaGrinTongueSquint,
  FaGrinTongueWink,
  FaGrinWink,
  FaHammer,
  FaHandHolding,
  FaHandHoldingHeart,
  FaHandHoldingMedical,
  FaHandHoldingUsd,
  FaHandHoldingWater,
  FaHandPaper,
  FaHandRock,
  FaHanukiah,
  FaHatCowboy,
  FaHatCowboySide,
  FaHatWizard,
  FaHeadphones,
  FaHeadphonesAlt,
  FaHeadset,
  FaKiss,
  FaKissBeam,
  FaKissWinkHeart,
  FaKiwiBird,
  FaLaugh,
  FaLaughBeam,
  FaLaughSquint,
  FaLaughWink,
  FaHelicopter,
  FaHiking,
  FaHippo,
  FaHornbill,
  FaHorseHead,
  FaHotTub,
  FaHotdog,
  FaIgloo,
  FaJoomla,
  FaJournalWhills,
  FaKaaba,
  FaKeycdn,
  FaKhanda,
  FaFrownOpen,
  Fa500Px,
  FaAccessibleIcon,
  FaAccusoft,
  FaAcquisitionsIncorporated,
  FaAd,
  FaAddressBook,
  FaAddressCard,
  FaAdjust,
  FaAdn,
  FaAdversal,
  FaAffiliatetheme,
  FaAirFreshener,
  FaAirbnb,
  FaAlgolia,
  FaAllergies,
  FaAmazonPay,
  FaAmericanSignLanguageInterpreting,
  FaAngry,
  FaAngrycreative,
  FaAnkh,
  FaApper,
  FaArchway,
  FaArrowAltCircleDown,
  FaAsymmetrik,
  FaAsterisk,
  FaAtom,
  FaBabyCarriage,
  FaAutoprefixer,
  FaBaby,
  FaAvianex,
  FaBalanceScale,
  FaBandcamp,
  FaBaseballBall,
  FaBath,
  FaBattleNet,
  FaBeer,
  FaBiking,
  FaBinoculars,
  FaBirthdayCake,
  FaBlog,
  FaBomb,
  FaBone,
  FaBong,
  FaBrain,
  FaBoxOpen,
  FaBriefcaseMedical,
  FaBuilding,
  FaBullhorn,
  FaBus,
  FaBusinessTime,
  FaCameraRetro,
  FaCamera,
  FaCampground,
  FaCannabis,
  FaCat,
  FaChessKnight,
  FaChessQueen,
  FaChurch,
  FaCity,
  FaCloudflare,
  FaCode,
  FaComments,
  FaCommentMedical,
  FaCompass,
  FaCookie,
  FaCreditCard,
  FaCriticalRole,
  FaCrown,
  FaCrow,
  FaCrosshairs,
  FaCubes,
  FaCube,
  FaDesktop,
  FaDiceD20,
  FaDigitalOcean,
  FaDochub,
  FaDove,
  FaDolly,
  FaDraftingCompass,
  FaDragon,
  FaDrawPolygon,
  FaDribbble,
  FaDribbbleSquare,
  FaDrupal,
  FaDrumSteelpan,
  FaDyalog,
  FaElementor,
  FaEnvira,
  FaEmpire,
  FaEmber,
  FaEthereum,
  FaExclamationCircle,
  FaEthernet,
  FaEuroSign,
  FaFaucet,
  FaFax,
  FaFeather,
  FaFedora,
  FaFish,
  FaFistRaised,
  FaFlushed,
  FaFly,
  FaForumbee,
  FaFortAwesomeAlt,
  FaFrog,
  FaGalacticRepublic,
  FaGalacticSenate,
  FaGavel,
  FaGlassMartiniAlt,
  FaGlobe,
  FaGlasses,
  FaGlassCheers,
  FaGitlab,
  FaGitkraken,
  FaGlobeEurope,
  FaGrav,
  FaKey,
  FaPiggyBank,
  FaQuidditch,
  FaRobot,
  FaRoad,
  FaRocket,
  FaRust,
  FaSatellite,
  FaSatelliteDish,
  FaSchool,
  FaShapes,
  FaSkating,
  FaSleigh,
  FaSmoking,
  FaSmokingBan,
  FaStethoscope,
  FaUserNurse,
  FaUtensils,
  FaYammer,
  FaYarn,
  FaYinYang,
  FaWizardsOfTheCoast,
  FaWaze,
  FaWeebly,
  FaJenkins,
];
